title: RYTES Company
description: Source of truth for all style and branding related to RYTES Company
theme: just-the-docs

url: https://skellyrytes.github.io/rytesstyleguide

aux_links:
  Template Repository: https://github.com/skellyrytes/rytesstyleguide

color_scheme: dark

callouts:
  warning:
    title: Warning
    color: red
  important:
    title: Important
    color: blue
  highlight:
    title: Highlight
    color: yellow
  note:
    title: Note
    color: purple
  new:
    title: New
    color: green
